# Generated by Django 4.2.3 on 2023-10-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=130)),
                ('time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
