# Generated by Django 4.2.3 on 2023-09-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('phone', models.IntegerField(max_length=9)),
            ],
        ),
    ]
